export default class actionConstant {
    static SET_EMAIL = "SET_EMAIL";
    static SET_PASSWORD = "SET_PASSWORD";
    static ENABLE_BUTTON = "ENABLE_BUTTON";
    static LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
    static LOGGED_FAILED = "LOGGED_FAILED";
    static LOGGED_SUCCESSFULLY = "LOGGED_SUCCESSFULLY";
    static LOGOUT = "LOGOUT";
    static GET_STUDENT = "GET_STUDENT";
    static GET_COURSE = "GET_COURSE";
    static GET_TEACHER = "GET_TEACHER";
    static GET_CLASS = "GET_CLASS";
    static IS_MODAL_OPEN = "IS_MODAL_OPEN";
    static RAW_DETECT = "RAW_DETECT"
    static NEW_ADDED_ID = "NEW_ADDED_ID"
    static RESET_ID= "RESET_ID"
    static GET_AVAILABLE_TEACHERS = 'GET_AVAILABLE_TEACHERS'
    static GET_AVAILABLE_CLASSES = 'GET_AVAILABLE_CLASSES'};
